version: '3.8'

networks:
  roomres-network:
    driver: bridge

services:
  # ==========================================
  # 1. INFRAESTRUTURA DE DADOS E MENSAGERIA
  # ==========================================
  user-db:
    image: postgres:15-alpine
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_pass
    networks:
      - roomres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_user -d user_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  room-db:
    image: postgres:15-alpine
    container_name: room-db
    environment:
      POSTGRES_DB: room_db
      POSTGRES_USER: room_user
      POSTGRES_PASSWORD: room_pass
    networks:
      - roomres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U room_user -d room_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  booking-db:
    image: postgres:15-alpine
    container_name: booking-db
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
    networks:
      - roomres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booking_user -d booking_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  audit-db:
    image: postgres:15-alpine
    container_name: audit-db
    environment:
      POSTGRES_DB: audit_db
      POSTGRES_USER: audit_user
      POSTGRES_PASSWORD: audit_pass
    networks:
      - roomres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U audit_user -d audit_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "15672:15672" # Painel Visual do RabbitMQ (Login: guest/guest)
    networks:
      - roomres-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - roomres-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - roomres-network

  redis:
    image: redis:7-alpine
    container_name: room-reservation-redis
    networks:
      - roomres-network

  # ==========================================
  # 2. OBSERVABILIDADE E MÉTRICAS (FASE 3)
  # ==========================================
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411" # Acesso ao Painel do Zipkin (Distributed Tracing)
    networks:
      - roomres-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      # Lembre-se de ter o arquivo prometheus.yml na mesma pasta deste docker-compose!
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - roomres-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - roomres-network

  # ==========================================
  # 3. MICROSSERVIÇOS LOCAIS (BUILD DIRETO)
  # ==========================================
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - roomres-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8761/actuator/health"]
      interval: 15s
      retries: 5
      start_period: 30s

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      user-db:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user_db
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-dummy}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:-dummy}
    networks:
      - roomres-network

  room-service:
    build: ./room-service
    container_name: room-service
    depends_on:
      room-db:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://room-db:5432/room_db
      - SPRING_DATA_REDIS_HOST=redis
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    networks:
      - roomres-network

  booking-service:
    build: ./booking-service
    container_name: booking-service
    depends_on:
      booking-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      kafka:
        condition: service_started
      discovery-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://booking-db:5432/booking_db
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    networks:
      - roomres-network

  audit-service:
    build: ./audit-service
    container_name: audit-service
    depends_on:
      audit-db:
        condition: service_healthy
      kafka:
        condition: service_started
      discovery-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://audit-db:5432/audit_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    networks:
      - roomres-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
      rabbitmq:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - MAIL_USERNAME=${MAIL_USERNAME:-dummy}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-dummy}
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    networks:
      - roomres-network

  suggestion-service:
    build: ./suggestion-service
    container_name: suggestion-service
    environment:
      - ROOM_SERVICE_URL=http://room-service:8082
    networks:
      - roomres-network

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080" # Única porta exposta para a internet pública!
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    networks:
      - roomres-network