server:
  port: 8083

spring:
  application:
    name: booking-service

  # Forçamos o perfil 'prod' ou 'default' para ignorar o 'dev' antigo que aponta para a porta 5440
  profiles:
    active: default

  datasource:
    # Nova porta 5443 para o booking_db isolado (Microsserviços Nível 2)
    url: jdbc:postgresql://localhost:5440/booking_db
    username: booking_user
    password: booking_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

# Configuração do SpringDoc para documentação
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Configurações de log para facilitar o debug da migração
logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    com.roomres.booking_service: DEBUG

# --- NOVO: CONFIGURAÇÃO DO EUREKA CLIENT ---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      roomServiceCB:
        registerHealthIndicator: true
        # Janela de 10 chamadas para análise
        slidingWindowSize: 10
        # Permite 3 chamadas de teste quando o circuito está "Meio Aberto"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        # Mínimo de chamadas antes de calcular a taxa de falha
        minimumNumberOfCalls: 5
        # Tempo que o circuito fica "Aberto" antes de tentar recuperar (5 segundos)
        waitDurationInOpenState: 5s
        # Se 50% das chamadas falharem, o circuito abre
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

# Configuração de Observabilidade e Tracing
management:
  tracing:
    sampling:
      probability: 1.0 # 1.0 significa 100% (Rastreia TODAS as requisições). Em prod, seria 0.1 (10%) para poupar recursos.
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"