server:
  port: 8082

spring:
  application:
    name: room-service
  datasource:
    url: jdbc:postgresql://localhost:5442/room_db
    username: room_user
    password: room_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# --- NOVO: CONFIGURAÇÃO DO EUREKA CLIENT ---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Configuração de Observabilidade e Tracing
management:
  tracing:
    sampling:
      probability: 1.0 # 1.0 significa 100% (Rastreia TODAS as requisições). Em prod, seria 0.1 (10%) para poupar recursos.
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"