server:
  port: 8082

spring:
  application:
    name: room-service
  datasource:
    url: jdbc:postgresql://localhost:5442/room_db
    username: room_user
    password: room_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

# Swagger Config
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html