server:
  port: 8080 # O único IP/Porta que o mundo externo verá

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Permite encontrar serviços pelo nome no Eureka

      # MAPEAMENTO DE ROTAS
      routes:
        - id: user-service-route
          uri: lb://user-service # lb = Load Balancer (usa o nome no Eureka)
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**

        - id: room-service-route
          uri: lb://room-service
          predicates:
            - Path=/api/v1/rooms/**

        - id: booking-service-route
          uri: lb://booking-service
          predicates:
            - Path=/api/v1/bookings/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/