#H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Aqui o Hibernate pode criar as tabelas sozinho para os testes
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Flyway desligado nos testes simples
spring.flyway.enabled=false