spring.profiles.active=dev
spring.application.name=reservation

# Muda o caminho da interface visual
springdoc.swagger-ui.path=/swagger

# Muda o caminho do JSON da documentacao
springdoc.api-docs.path=/api-docs