#Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5440/reservation_db
spring.datasource.username=postgres
spring.datasource.password=postgrespassword


#Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-plataform=org.hibernate.dialect.PostgreSQLDialect

#Flyway
spring.flyway.enabled-true