# A porta que a aplicacao usa em producao/desenvolvimento local
quarkus.http.port=8086


# Permite receber conexões externas (do API Gateway)
quarkus.http.host=0.0.0.0


# CI/CD Hotfix: Define a porta de teste como 0 (Zero).
quarkus.http.test-port=0


# Nome do serviço
quarkus.application.name=suggestion-service


# NOVA REGRA: Rota Dinâmica do REST Client
# Se o Docker enviar a variável ROOM_SERVICE_URL, ele usa. Senão, assume localhost (para testes locais).
room-api/mp-rest/url=${ROOM_SERVICE_URL:http://localhost:8082}


# ==========================================
# CONFIGURAÇÃO DE OBSERVABILIDADE E MÉTRICAS
# ==========================================
# Dizemos ao Micrometer para etiquetar todas as métricas com application="suggestion-service"
quarkus.micrometer.binder.global-tags.application=${quarkus.application.name}