# A porta que a aplicacao usa em producao/desenvolvimento local
quarkus.http.port=8086

# CORREÇÃO DO DOCKER: Permite receber conexões externas (do API Gateway)
quarkus.http.host=0.0.0.0

# CI/CD Hotfix: Define a porta de teste como 0 (Zero).
# Isso forca o Quarkus a escolher uma porta aleatoria disponivel na maquina do GitHub Actions,
# eliminando 100% das chances de conflito de "Address already in use" na esteira.
quarkus.http.test-port=0
# Nome do serviço
quarkus.application.name=suggestion-service