name: Integracao Continua - Microsservicos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false # NOVO: Se um serviço falhar, NÃO cancela os outros! Testa todos.
      matrix:
        service: 
          - user-service
          - room-service
          - booking-service
          - audit-service
          - notification-service
          - discovery-service
          - gateway-service

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # NOVO: Sobe toda a nossa infraestrutura usando o arquivo docker-compose.yml da raiz
    - name: Subir Infraestrutura de Apoio (Docker Compose)
      run: docker compose up -d

    # NOVO: Dá 20 segundos de fôlego para o Postgres, Kafka e RabbitMQ iniciarem completamente
    - name: Aguardar prontidão dos bancos e mensageria
      run: sleep 20

    - name: Build e Testes Automáticos (${{ matrix.service }})
      working-directory: ./${{ matrix.service }}
      run: mvn clean verify

    # NOVO: Limpa a casa depois (roda sempre, mesmo se a etapa de testes der erro)
    - name: Desligar Infraestrutura
      if: always()
      run: docker compose down