name: Integracao Continua e Deploy (CI/CD)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - user-service
          - room-service
          - booking-service
          - audit-service
          - notification-service
          - discovery-service
          - gateway-service
          - suggestion-service

    steps:
      - name: Baixar o codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar o Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # BUILD E TESTES COM TESTCONTAINERS NATIVO DO GITHUB ACTIONS
      - name: Build e Testes Automaticos (Spring Boot)
        if: ${{ matrix.service != 'suggestion-service' }}
        working-directory: ./${{ matrix.service }}
        run: |
          if [ "${{ matrix.service }}" == "discovery-service" ] || [ "${{ matrix.service }}" == "gateway-service" ] || [ "${{ matrix.service }}" == "notification-service" ]; then
            mvn clean install -DskipTests
          else
            #CORREÇÃO 3.3: Sem -DskipTests! O Testcontainers vai gerir a infraestrutura de testes!
            mvn clean verify -Dspring.cloud.discovery.enabled=false -Dspring.cloud.config.enabled=false -Dspring.cloud.service-registry.auto-registration.enabled=false
          fi

      - name: Build Automatico (Quarkus)
        if: ${{ matrix.service == 'suggestion-service' }}
        working-directory: ./${{ matrix.service }}
        run: mvn clean package -Dquarkus.build.skip=false

      # DEPLOY CONTINUO (DOCKER HUB)
      - name: Login no Docker Hub
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e Publicar Imagem Docker
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ./${{ matrix.service }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest